In [4]:
import pandas as pd

In [5]:
df = pd.read_csv('D:/files/dota_hero_stats.csv')
df

,Unnamed: 0,attack_type,id,legs,localized_name,name,primary_attr,roles
0,0,Melee,1,2,Anti-Mage,npc_dota_hero_antimage,agi,"['Carry', 'Escape', 'Nuker']"
1,1,Melee,2,2,Axe,npc_dota_hero_axe,str,"['Initiator', 'Durable', 'Disabler', 'Jungler']"
2,2,Ranged,3,4,Bane,npc_dota_hero_bane,int,"['Support', 'Disabler', 'Nuker', 'Durable']"
3,3,Melee,4,2,Bloodseeker,npc_dota_hero_bloodseeker,agi,"['Carry', 'Disabler', 'Jungler', 'Nuker', 'Ini..."
4,4,Ranged,5,2,Crystal Maiden,npc_dota_hero_crystal_maiden,int,"['Support', 'Disabler', 'Nuker', 'Jungler']"
...,...,...,...,...,...,...,...,...
112,112,Melee,114,2,Monkey King,npc_dota_hero_monkey_king,agi,"['Carry', 'Escape', 'Disabler', 'Initiator']"
113,113,Ranged,119,2,Dark Willow,npc_dota_hero_dark_willow,int,"['Support', 'Nuker', 'Disabler', 'Escape']"
114,114,Melee,120,2,Pangolier,npc_dota_hero_pangolier,agi,"['Carry', 'Nuker', 'Disabler', 'Durable', 'Esc..."
115,115,Ranged,121,2,Grimstroke,npc_dota_hero_grimstroke,int,"['Support', 'Nuker', 'Disabler', 'Escape']"
116,116,Melee,129,2,Mars,npc_dota_hero_mars,str,"['Carry', 'Initiator', 'Disabler', 'Durable']"

In [6]:
# задание Easy урок 2
df.groupby(['legs'])['name'].count()

legs
0    11
2    95
4     7
6     3
8     1
Name: name, dtype: int64

In [7]:
# задание Medium урок 2
df.groupby(['attack_type', 'primary_attr']).count()
# смотрим количество по группировке, видим, что самые популярные это Ranged и intb

                          Unnamed: 0  id  legs  localized_name  name  roles
attack_type primary_attr
Melee       agi                   19  19    19              19    19     19
            int                    2   2     2               2     2      2
            str                   35  35    35              35    35     35
Ranged      agi                   18  18    18              18    18     18
            int                   40  40    40              40    40     40
            str                    3   3     3               3     3      3

In [8]:
df[(df['attack_type'] == 'Ranged') & (df['primary_attr'] == 'int')]['localized_name']
# выводим список героев по известным характеристикам

2                     Bane
4           Crystal Maiden
12                    Puck
16            Storm Spirit
20              Windranger
21                    Zeus
23                    Lina
24                    Lion
25           Shadow Shaman
28            Witch Doctor
29                    Lich
31                  Enigma
32                  Tinker
34               Necrophos
35                 Warlock
37           Queen of Pain
41           Death Prophet
43                   Pugna
48                  Dazzle
50                 Leshrac
51        Nature's Prophet
56             Enchantress
62                  Jakiro
63                Batrider
64                    Chen
66      Ancient Apparition
72                 Invoker
73                Silencer
74       Outworld Devourer
77            Shadow Demon
84                  Rubick
85               Disruptor
88     Keeper of the Light
90                  Visage
99           Skywrath Mage
103                Techies
109                 Oracle
110          Winter Wyvern
113            Dark Willow
115             Grimstroke
Name: localized_name, dtype: object

In [9]:
df[df['localized_name'] == 'Jakiro']
# проверяем выборочной проверкой характеристики

,Unnamed: 0,attack_type,id,legs,localized_name,name,primary_attr,roles
62,62,Ranged,64,2,Jakiro,npc_dota_hero_jakiro,int,"['Support', 'Nuker', 'Pusher', 'Disabler']"